# ------------------------------------------------------------
# CONTENT DATA FOR PORTFOLIO APP
# ------------------------------------------------------------

metrics = [
    ("3×", "Revenue growth achieved through startup operations and commercialization"),
    ("2,000+", "Live learning sessions delivered in a high-volume EdTech environment"),
    ("150+", "Monthly conversions contributed through engagement and performance insights"),
    ("$3.5M", "Commercial proposal structured for enterprise transformation"),
    ("100+", "Primary research responses used for market and customer insight"),
    ("10+", "Expert / stakeholder interviews across transformation research"),
    ("14+", "Projects and analytics workstreams across strategy, operations, AI and BI"),
    ("5+", "Years across healthcare, EdTech, startup operations and business projects"),
]

portfolio_fit_areas = [
    {
        "area": "Business ownership & execution",
        "evidence": "Turfo operating ownership, BYJU’S high-volume delivery, clinical care coordination and MBA transformation projects.",
    },
    {
        "area": "Commercial thinking",
        "evidence": "Bunk Station turnaround logic, GSK market entry model, Royal Dutch growth strategy and enterprise proposal work.",
    },
    {
        "area": "Data analytics & BI",
        "evidence": "TasteMate analytics dashboard, Turfo revenue/utilisation trackers, BYJU’S performance insights and AI adoption modelling.",
    },
    {
        "area": "AI-powered business models",
        "evidence": "FinWise AI-enabled MVP, Smart Hospitals digital transformation, AI adoption research and workflow automation thinking.",
    },
    {
        "area": "Stakeholder activation",
        "evidence": "Learning experience design, patient/customer journey mapping, expert interviews, partner/vendor coordination and event leadership.",
    },
    {
        "area": "Market intelligence",
        "evidence": "GSK oncology market assessment, TrueLayer open banking analysis, DP World ecosystem strategy and healthcare growth research.",
    },
]

projects = [
    {
        "title": "Bunk Station – Strategic Turnaround & Investment Roadmap",
        "capability": "Commercial Strategy & Unit Economics",
        "location": "Dubai",
        "context": "Live consulting-style F&B turnaround project",
        "image": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1400&q=85",
        "summary": "Developed a strategic turnaround plan by diagnosing market demand, customer segments, branding gaps, operational inefficiency and revenue growth opportunities.",
        "problem": "Bunk Station had strong fundamentals such as best-selling SKUs and a student customer base, but weak visibility, poor ratings, branding gaps and operational inefficiency.",
        "role": "Conducted business diagnosis and recommended an investment-led repositioning strategy instead of maintaining status quo or shutting down.",
        "approach": [
            "Analysed DIAC student market demand and customer personas.",
            "Reviewed brand positioning, menu architecture, operations and competitive context.",
            "Identified bottlenecks around visibility, service speed and revenue conversion.",
            "Developed a turnaround roadmap covering menu engineering, combo pricing, QR ordering, loyalty programs and KPI tracking.",
        ],
        "frameworks": ["Turnaround Strategy", "Customer Persona", "Menu Engineering", "KPI Tracking", "Investment Decision"],
        "tools": ["PowerPoint", "Market analysis", "Primary research", "Financial logic"],
        "outputs": [
            "Strategic turnaround recommendation.",
            "Investment-led repositioning plan.",
            "Menu and combo pricing strategy.",
            "QR-based ordering and KPI roadmap.",
            "Revenue growth and operating efficiency logic.",
        ],
        "strategic_relevance": "Strong evidence of commercial diagnosis, growth planning, KPI thinking, customer acquisition and operating improvement.",
    },
    {
        "title": "TrueLayer – Open Banking Strategy & Ecosystem Assessment",
        "capability": "Ecosystem Development",
        "location": "Dubai",
        "context": "Enterprise Innovation & Digital Transformation case analysis",
        "image": "https://images.unsplash.com/photo-1559526324-593bc073d938?auto=format&fit=crop&w=1400&q=85",
        "summary": "Assessed TrueLayer’s open banking platform by analysing how regulation, APIs and ecosystem partnerships enable fintech innovation and competitive advantage.",
        "problem": "Open banking platforms must balance regulation, trust, API infrastructure, ecosystem partnerships and market readiness to scale effectively.",
        "role": "Conducted a strategic assessment of TrueLayer’s platform model, regulatory context and expansion opportunities.",
        "approach": [
            "Analysed PSD2, API infrastructure and open banking regulation.",
            "Evaluated market expansion opportunities using readiness and demand criteria.",
            "Assessed operating model capabilities such as compliance agility, scalability and ecosystem integration.",
            "Linked platform strategy to financial services business model innovation.",
        ],
        "frameworks": ["Platform Strategy", "Open Banking", "API Ecosystem", "Regulatory Strategy", "Market Expansion"],
        "tools": ["Case analysis", "PowerPoint", "Strategic frameworks", "Secondary research"],
        "outputs": [
            "Open banking strategy assessment.",
            "Market expansion prioritisation logic.",
            "Operating model capability review.",
            "Ecosystem partnership analysis.",
        ],
        "strategic_relevance": "Relevant to ecosystem development, platform partnerships, regulated fintech analysis, market readiness and expansion logic.",
    },
    {
        "title": "FinWise – AI-Powered Financial Literacy Platform",
        "capability": "AI-Powered Business Models",
        "location": "UAE",
        "context": "AI-enabled B2B2C education/product strategy",
        "image": "https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=1400&q=85",
        "summary": "Designed a scalable AI-enabled financial literacy model for students, parents, schools and CSR partners with structured learning journeys and implementation logic.",
        "problem": "Financial literacy gaps among school-aged learners are driven by curriculum gaps, behavioural gaps, parental engagement gaps and system constraints.",
        "role": "Structured the product concept, stakeholder model, MVP logic, journey maps, service blueprint and scale roadmap.",
        "approach": [
            "Defined target stakeholders: students, parents, schools and sponsors.",
            "Mapped learning journeys and behavioural reinforcement logic.",
            "Structured B2B2C operating model and partner-led rollout.",
            "Developed TOWS, service blueprint and governance logic.",
        ],
        "frameworks": ["TOWS", "Service Blueprint", "Customer Journey", "B2B2C Model", "MVP Design"],
        "tools": ["PowerPoint", "AI tools", "Business model design", "Journey mapping"],
        "outputs": [
            "AI-enabled MVP structure.",
            "Student-parent-school journey map.",
            "Service blueprint.",
            "3-year scale roadmap.",
        ],
        "strategic_relevance": "Shows AI-enabled workflow thinking, stakeholder ecosystems, onboarding journeys and scalable operating model design.",
    },
    {
        "title": "LM Instruments – SAP S/4HANA Transformation Strategy",
        "capability": "Enterprise Transformation",
        "location": "Dubai",
        "context": "SAP transformation RFP and commercial model",
        "image": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1400&q=85",
        "summary": "Structured AS-IS / TO-BE workflows, SAP-aligned operating blueprints, data migration logic and commercial proposal for enterprise transformation.",
        "problem": "Enterprise transformation requires clear process design, data readiness, governance, cost logic and implementation sequencing across functions.",
        "role": "Mapped business requirements, process dependencies, data entities and commercial proposal logic.",
        "approach": [
            "Structured AS-IS and TO-BE workflows across enterprise functions.",
            "Translated business inputs into SAP-aligned process blueprints.",
            "Defined data migration and validation logic across critical entities.",
            "Built commercial model with cost, margin and governance assumptions.",
        ],
        "frameworks": ["AS-IS / TO-BE", "RFP Response", "Operating Blueprint", "Governance Model"],
        "tools": ["Excel", "PowerPoint", "Process mapping", "Cost modelling"],
        "outputs": [
            "5+ enterprise workflow maps.",
            "SAP-aligned operating blueprint.",
            "Data validation logic across 6+ entities.",
            "$3.5M commercial proposal with margin logic.",
        ],
        "strategic_relevance": "Shows structured process thinking, data workflow design, governance and commercial model discipline.",
    },
    {
        "title": "DP World – Digital Trade & Supply Chain Transformation",
        "capability": "Digital Transformation",
        "location": "Dubai",
        "context": "Emerging technology strategy project",
        "image": "https://images.unsplash.com/photo-1494412651409-8963ce7935a7?auto=format&fit=crop&w=1400&q=85",
        "summary": "Assessed how AI, blockchain, AR/VR and drones can improve trade visibility, logistics efficiency, documentation speed and operational resilience.",
        "problem": "Trade and logistics ecosystems face inefficiencies across documentation, customs, visibility, yard planning and asset monitoring.",
        "role": "Conducted use-case analysis, operating model assessment and technology-to-business-impact mapping.",
        "approach": [
            "Assessed emerging technology use cases across trade operations.",
            "Mapped impact across customs, cargo visibility, workforce enablement and asset monitoring.",
            "Linked automation and digital workflows to operational throughput and documentation improvements.",
            "Structured recommendations around efficiency, trust and resilience.",
        ],
        "frameworks": ["Emerging Tech Strategy", "Use-Case Prioritisation", "Operating Model", "Digital Trade Ecosystem"],
        "tools": ["PowerPoint", "Research synthesis", "Benchmarking", "Process analysis"],
        "outputs": [
            "Emerging technology use-case map.",
            "Digital trade ecosystem assessment.",
            "Operational improvement logic.",
            "Strategic recommendation deck.",
        ],
        "strategic_relevance": "Relevant for global ecosystem thinking, emerging technology, operational visibility and cross-border commercial environments.",
    },
    {
        "title": "Royal Dutch Clinic – Growth Strategy & Operating Model Analysis",
        "capability": "Healthcare Growth Strategy",
        "location": "UAE",
        "context": "Healthcare growth and operating model project",
        "image": "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1400&q=85",
        "summary": "Assessed growth potential, patient journey, referral pathways, pricing sensitivity and operational bottlenecks for a premium healthcare services context.",
        "problem": "Healthcare service growth can be constrained by unclear patient acquisition pathways, pricing friction, operational bottlenecks and inconsistent service conversion.",
        "role": "Supported market and operational analysis using primary research, benchmarking and patient journey assessment.",
        "approach": [
            "Analysed patient journey and inquiry-to-appointment funnel.",
            "Reviewed referral pathways and competitive healthcare landscape.",
            "Used 100+ primary research responses for demand and pricing insights.",
            "Recommended service, pricing and operating model improvements.",
        ],
        "frameworks": ["Patient Journey Mapping", "Operating Model", "Growth Strategy", "Customer Insight"],
        "tools": ["Excel", "Survey analysis", "PowerPoint", "Benchmarking"],
        "outputs": [
            "Growth strategy recommendations.",
            "Patient funnel and service workflow insights.",
            "Pricing and demand observations.",
            "Operating model improvement priorities.",
        ],
        "strategic_relevance": "Shows customer acquisition logic, stakeholder mapping, service conversion thinking and operating model improvement.",
    },
    {
        "title": "GSK – U.S. Oncology Market Entry & Commercial Strategy",
        "capability": "Market Intelligence",
        "location": "Dubai",
        "context": "Global strategy project",
        "image": "https://images.unsplash.com/photo-1579154341098-e4e158cc7f55?auto=format&fit=crop&w=1400&q=85",
        "summary": "Analysed U.S. oncology market opportunity, competitive landscape, commercial positioning and investment logic for a new prostate cancer drug context.",
        "problem": "Pharma market entry requires clarity on market attractiveness, competitive differentiation, pricing logic, stakeholder access and investment feasibility.",
        "role": "Worked on market intelligence, competitive benchmarking, financial modelling and commercial strategy framing.",
        "approach": [
            "Assessed oncology market size and growth context.",
            "Benchmarked competitor positioning and portfolio overlaps.",
            "Structured stakeholder ecosystem across HCPs, payers and institutions.",
            "Built scenario-led financial and launch logic.",
        ],
        "frameworks": ["Market Entry Strategy", "Competitor Benchmarking", "Scenario Analysis", "Commercial Strategy"],
        "tools": ["Excel", "PowerPoint", "Secondary research", "Financial modelling"],
        "outputs": [
            "U.S. oncology market assessment.",
            "Competitive benchmarking and whitespace logic.",
            "5-year financial model.",
            "Pricing and investment recommendation logic.",
        ],
        "strategic_relevance": "Relevant to market intelligence, competitor benchmarking, commercial modelling and executive-level commercial recommendation.",
    },
    {
        "title": "Smart Hospitals – Digital Transformation Strategy",
        "capability": "Healthcare Digital Transformation",
        "location": "Singapore",
        "context": "SingHealth-focused academic consulting project",
        "image": "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=1400&q=85",
        "summary": "Designed a healthcare digital transformation roadmap focused on interoperability, workflow standardisation, KPI governance, digital adoption and patient journey improvement.",
        "problem": "Hospitals often face fragmented workflows, uneven digital adoption, interoperability gaps and weak KPI visibility across patient-facing and back-office processes.",
        "role": "Conducted research, synthesised expert and patient inputs, assessed workflow adoption gaps and structured the SMART-DX transformation framework.",
        "approach": [
            "Mapped patient journey and hospital workflow pain points.",
            "Reviewed digital maturity benchmarks and transformation barriers.",
            "Synthesised expert interviews, patient inputs and healthcare evidence.",
            "Developed a SMART-DX framework and 3-year transformation roadmap.",
        ],
        "frameworks": ["SMART-DX", "TOWS", "Scenario Analysis", "KPI Governance", "Stakeholder Mapping"],
        "tools": ["Excel", "PowerPoint", "Research synthesis", "Interview analysis"],
        "outputs": [
            "SMART-DX digital transformation framework.",
            "3-year roadmap for standardisation, integration and automation.",
            "KPI-led governance recommendations.",
            "Patient journey and workflow improvement priorities.",
        ],
        "strategic_relevance": "Relevant to AI-enabled operational redesign, KPI governance, stakeholder adoption and transformation roadmap thinking.",
    },
    {
        "title": "Clinical Operations – Consultation Flow & Care Coordination",
        "capability": "Healthcare Operations",
        "location": "India",
        "context": "Dental clinic and hospital-linked clinical workflow experience",
        "image": "https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=1400&q=85",
        "summary": "Managed patient consultation flow, documentation, follow-ups, staff coordination and external lab/vendor coordination across clinical workflows.",
        "problem": "Clinical service quality depends on disciplined documentation, timely follow-ups, staff coordination, patient communication and material readiness.",
        "role": "Coordinated consultation workflows, treatment documentation, patient follow-ups and service readiness across clinical and support stakeholders.",
        "approach": [
            "Managed consultation flow and patient documentation.",
            "Coordinated with staff and external labs for treatment readiness.",
            "Supported follow-up communication and continuity of care.",
            "Strengthened documentation discipline and service coordination.",
        ],
        "frameworks": ["Patient Flow", "Clinical Documentation", "Care Coordination", "Service Operations"],
        "tools": ["Clinical records", "Scheduling", "Follow-up tracking", "Stakeholder coordination"],
        "outputs": [
            "Structured patient documentation.",
            "Improved follow-up discipline.",
            "Coordinated staff and lab workflows.",
            "Supported smoother patient experience.",
        ],
        "strategic_relevance": "Relevant to lifecycle discipline: structured follow-ups, service coordination, operational clarity and stakeholder communication.",
    },
]

analytics_projects = [
    {
        "title": "TasteMate Cloud Kitchen – End-to-End Analytics Dashboard",
        "capability": "Customer Analytics & Decision Intelligence",
        "location": "Academic / Business Analytics Project",
        "context": "Cloud kitchen analytics project using customer and transaction data",
        "image": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1400&q=85",
        "summary": "Designed an end-to-end analytics dashboard framework connecting customer behaviour, revenue drivers, segmentation, predictive modelling and recommendation logic to business decisions.",
        "problem": "Cloud kitchens need more than sales reports. They need visibility into customer behaviour, spend drivers, loyalty patterns, retention risk, meal combinations and pricing opportunities.",
        "role": "Owned the analytics storyline from business problem framing to dashboard logic, modelling choices, insight generation and business recommendations.",
        "approach": [
            "Cleaned and transformed customer and transaction-level data for analysis.",
            "Used EDA to understand demand, spend behaviour and operational patterns.",
            "Used clustering to segment customers into behavioural personas.",
            "Used regression to model average spend and support pricing and packaging decisions.",
            "Applied classification models for prediction-oriented customer and business decisions.",
            "Used association rule mining to identify revenue-driving meal combinations.",
            "Designed Streamlit dashboard tabs for visualisation, model comparison and business insights.",
        ],
        "frameworks": ["EDA", "Customer Segmentation", "Regression", "Classification", "Clustering", "Association Rule Mining"],
        "tools": ["Python", "Streamlit", "Pandas", "Scikit-learn", "Plotly", "Excel"],
        "outputs": [
            "Interactive analytics dashboard structure.",
            "Customer segmentation logic.",
            "Average spend modelling approach.",
            "Classification model comparison.",
            "Association rules for meal combination insights.",
            "Business recommendations for pricing, campaigns and retention.",
        ],
        "strategic_relevance": "Shows ownership of analytics as a decision system: from raw data to insight, model logic, dashboarding and commercial recommendations.",
    },
    {
        "title": "Turfo Revenue & Utilization Analytics",
        "capability": "Operational Analytics & KPI Ownership",
        "location": "India",
        "context": "Startup operations analytics and dashboard-led decision-making",
        "image": "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1400&q=85",
        "summary": "Built operating trackers and dashboard logic to monitor bookings, pricing performance, utilisation and revenue trends, directly supporting business ownership and growth decisions.",
        "problem": "A growing sports facility needed visibility into slot demand, pricing efficiency, utilisation, customer engagement and revenue performance.",
        "role": "Owned the operating analytics layer by creating trackers, reviewing demand patterns and using performance data to support pricing, scheduling and utilisation decisions.",
        "approach": [
            "Built Excel dashboards for bookings, utilisation and revenue trends.",
            "Analysed customer demand patterns and peak-hour usage.",
            "Tracked weekly performance metrics across utilisation, revenue and engagement.",
            "Used insights to support pricing and scheduling improvements.",
            "Connected operational visibility with revenue growth decisions.",
        ],
        "frameworks": ["KPI Tracking", "Utilisation Analysis", "Revenue Analytics", "Pricing Analytics"],
        "tools": ["Excel", "Google Sheets", "Dashboard tracking", "Operational reporting"],
        "outputs": [
            "3× revenue growth in 8 months.",
            "Utilisation improved to approximately 60%.",
            "Structured booking and revenue trackers.",
            "Weekly operational performance visibility.",
        ],
        "strategic_relevance": "Direct evidence of dashboard-led business ownership, pricing analytics, utilisation analysis and operating performance tracking.",
    },
    {
        "title": "BYJU’S Engagement & Conversion Analytics",
        "capability": "Performance Analytics",
        "location": "India",
        "context": "High-volume EdTech performance and engagement analytics",
        "image": "https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=1400&q=85",
        "summary": "Used learner engagement and performance signals to identify learning gaps, refine delivery strategies and support conversion-oriented outcomes in a high-volume EdTech environment.",
        "problem": "Large-scale online learning delivery requires continuous visibility into engagement, learner gaps, feedback, session quality and conversion outcomes.",
        "role": "Used performance signals and learner feedback to improve session delivery, communication and student outcomes.",
        "approach": [
            "Reviewed learner engagement and performance dashboards.",
            "Identified learning gaps and adjusted session delivery strategies.",
            "Collected feedback and performance insights across live sessions.",
            "Supported engagement-led conversion outcomes.",
            "Worked in a target-driven performance environment.",
        ],
        "frameworks": ["Performance Analysis", "Engagement Analytics", "Learning Gap Analysis", "Conversion Support"],
        "tools": ["Internal dashboards", "Excel", "Performance reports", "Session analytics"],
        "outputs": [
            "2,000+ live sessions delivered.",
            "150+ monthly conversions contributed.",
            "Improved learner engagement and delivery quality.",
            "Top 20% month-on-month performance.",
        ],
        "strategic_relevance": "Shows ability to use performance data, feedback and dashboard insights to improve outcomes in a target-driven environment.",
    },
    {
        "title": "AI Adoption Research – TPB with Trust Mediation",
        "capability": "Research Analytics & Statistical Modelling",
        "location": "Academic research",
        "context": "Research Methods / SmartPLS project",
        "image": "https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?auto=format&fit=crop&w=1400&q=85",
        "summary": "Developed and analysed an AI adoption research model using the Theory of Planned Behavior with trust as a mediating variable.",
        "problem": "AI adoption is influenced by behavioural, trust, risk, self-efficacy and social expectation factors, requiring structured research modelling.",
        "role": "Designed the research model, reviewed literature, generated/analysed data and interpreted SmartPLS outputs.",
        "approach": [
            "Applied Theory of Planned Behavior constructs.",
            "Integrated trust as a mediating variable.",
            "Reviewed ABDC-rated literature.",
            "Analysed measurement and structural model outputs.",
            "Interpreted model quality, path relationships and adoption implications.",
        ],
        "frameworks": ["Theory of Planned Behavior", "PLS-SEM", "Trust Mediation", "Research Design"],
        "tools": ["SmartPLS", "Excel", "Literature review", "Statistical interpretation"],
        "outputs": [
            "Research framework.",
            "Measurement model interpretation.",
            "Structural model interpretation.",
            "Academic reflective report.",
        ],
        "strategic_relevance": "Shows research analytics, statistical reasoning, AI adoption insight and evidence-based decision-making.",
    },
]

experience = [
    {
        "title": "Co-Founder & Operations Lead – Turfo",
        "period": "Jan 2024 – Jan 2025 | India",
        "image": "https://images.unsplash.com/photo-1526232761682-d26e03ac148e?auto=format&fit=crop&w=1400&q=85",
        "description": "Built and operated a multi-sport play area business, managing daily operations, pricing, vendor coordination, partnerships, customer engagement, booking visibility and revenue tracking.",
        "achievements": [
            "Achieved 3× revenue growth in 8 months through pricing, utilisation and engagement improvements.",
            "Managed 35+ weekly engagements across bookings, customers, partners and operations.",
            "Built Excel trackers for bookings, revenue trends, utilisation and pricing performance.",
            "Improved utilisation to approximately 60% through demand pattern analysis and slot optimisation.",
            "Coordinated 5+ partnerships and vendor relationships while handling ground-level execution.",
        ],
    },
    {
        "title": "Academic Specialist – Biology – BYJU’S",
        "period": "Nov 2021 – Apr 2024 | India",
        "image": "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1400&q=85",
        "description": "Delivered live Biology sessions in a high-volume EdTech environment, combining teaching, learner engagement, performance feedback and conversion-supporting academic communication.",
        "achievements": [
            "Delivered 2,000+ live sessions across Biology learning modules.",
            "Contributed to 150+ monthly conversions through engagement and performance insights.",
            "Consistently performed in the top 20% month-on-month.",
            "Received awards for TAT and heavy lifting.",
            "Used learner performance patterns and feedback to improve delivery quality and student engagement.",
        ],
    },
    {
        "title": "Associate Dentist – Happy Smile Dental Clinic",
        "period": "Oct 2019 – Oct 2021 | India",
        "image": "https://images.unsplash.com/photo-1629909615184-74f495363b67?auto=format&fit=crop&w=1400&q=85",
        "description": "Managed patient care, treatment explanation, clinical documentation, consultation flow, follow-ups, staff coordination and external lab communication.",
        "achievements": [
            "Handled patient-facing consultation workflows and treatment plan communication.",
            "Maintained structured documentation and follow-up discipline.",
            "Coordinated with staff and external labs to support treatment readiness.",
            "Built strong grounding in healthcare operations, patient trust and service coordination.",
        ],
    },
]

education = [
    {
        "title": "Global MBA – SP Jain School of Global Management",
        "period": "Feb 2025 – Feb 2026 | Singapore · Dubai · India",
        "timeline": "2025 – 2026",
        "image": "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1400&q=85",
        "summary": "Global business education with exposure to strategy, consulting, finance, analytics, digital transformation, leadership and live business projects across multiple markets.",
        "highlights": [
            "Completed business projects across healthcare, fintech, enterprise transformation, life sciences, AI-enabled product strategy, data analytics and commercial modelling.",
            "Worked on consulting-style projects across Dubai, Singapore, UAE and India.",
            "Built commercial models, operating frameworks, market intelligence outputs and transformation recommendations.",
            "Conducted 100+ primary research responses and 10+ expert/stakeholder interviews across projects.",
        ],
    },
    {
        "title": "Fellowship in Medical Cosmetology – ILAMED",
        "period": "Aug 2020 – Feb 2021 | Chennai, India",
        "timeline": "2020 – 2021",
        "image": "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1400&q=85",
        "summary": "Fellowship in Medical Cosmetology from Institute of Laser & Aesthetic Medicine, Germany–India, in collaboration with University Medicine Greifswald, Germany.",
        "highlights": [
            "Focused on clinical dermatology and aesthetic medicine, including lasers, injectables, PRP/GFC therapy and chemical peels.",
            "Covered fundamentals of medical cosmetology, scope, ethics and evolution of aesthetic medicine.",
            "Built understanding of skin, hair and nail anatomy, Fitzpatrick scale and lesion identification.",
            "Strengthened evidence-based care, patient outcomes orientation and regulatory compliance awareness.",
        ],
    },
    {
        "title": "Bachelor of Dental Surgery – The Tamil Nadu Dr. M.G.R. Medical University",
        "period": "Sept 2014 – Sept 2019 | Chennai, India",
        "timeline": "2014 – 2019",
        "image": "https://images.unsplash.com/photo-1629909615184-74f495363b67?auto=format&fit=crop&w=1400&q=85",
        "summary": "Clinical healthcare foundation through a five-year BDS program with exposure to patient care, diagnosis, treatment planning, documentation, care coordination and healthcare communication.",
        "highlights": [
            "Completed 4 academic years plus 1-year compulsory rotatory internship.",
            "Built clinical grounding in patient care, diagnosis, treatment explanation and documentation.",
            "Developed healthcare workflow understanding through clinical exposure.",
            "Created the foundation for healthcare strategy, digital health and life sciences projects.",
        ],
    },
]

leadership_items = [
    {
        "title": "Global Learning & Student Life Committee",
        "category": "Student Leadership",
        "location": "SP Jain School of Global Management",
        "image": "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1400&q=85",
        "summary": "Supported cross-campus student engagement, coordination and student-faculty-admin communication during the Global MBA journey.",
        "skills": ["Leadership", "Coordination", "Student engagement", "Cross-functional communication"],
    },
    {
        "title": "Industry Connect Event",
        "category": "Industry Engagement",
        "location": "Dubai",
        "image": "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1400&q=85",
        "summary": "Supported an industry engagement event connecting students with senior business leaders and real-world decision-making discussions.",
        "skills": ["Event coordination", "Industry interface", "Stakeholder communication", "Execution"],
    },
    {
        "title": "Business Conclave",
        "category": "Leadership Event",
        "location": "Dubai",
        "image": "https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&w=1400&q=85",
        "summary": "Contributed to event coordination and student presentation support for a business leadership conclave.",
        "skills": ["Presentation support", "Logistics", "Team coordination", "Professional presence"],
    },
    {
        "title": "OMFS Awareness Marathon",
        "category": "Healthcare Outreach",
        "location": "Chennai",
        "image": "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1400&q=85",
        "summary": "Supported a public healthcare awareness event focused on oral and maxillofacial surgery awareness.",
        "skills": ["Healthcare outreach", "Public engagement", "Event execution", "Community awareness"],
    },
    {
        "title": "Anti-Tobacco Awareness Human Chain",
        "category": "Public Health",
        "location": "Chennai",
        "image": "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1400&q=85",
        "summary": "Participated in a public health awareness initiative promoting anti-tobacco education and preventive health communication.",
        "skills": ["Public health", "Community service", "Preventive health", "Awareness building"],
    },
]

extra_curricular_items = [
    {
        "title": "Live Communication & Public Speaking",
        "image": "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1400&q=85",
        "summary": "Built through 2,000+ live sessions, MBA presentations, stakeholder discussions and project delivery conversations.",
        "skills": ["Public speaking", "Live delivery", "Audience engagement", "Clarity"],
    },
    {
        "title": "Business Simulations & Strategy Games",
        "image": "https://images.unsplash.com/photo-1552664688-cf412ec27db2?auto=format&fit=crop&w=1400&q=85",
        "summary": "Worked on business simulation environments such as BOSS / Markstrat-style decision-making, market strategy and performance tracking.",
        "skills": ["Decision-making", "Market strategy", "Competitive thinking", "Scenario planning"],
    },
    {
        "title": "Dashboard & Portfolio Building",
        "image": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1400&q=85",
        "summary": "Built Streamlit dashboards and analytics-driven portfolio assets to present work, data and business evidence visually.",
        "skills": ["Streamlit", "Dashboarding", "Data storytelling", "Portfolio design"],
    },
    {
        "title": "Research Interviews & Insight Collection",
        "image": "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1400&q=85",
        "summary": "Conducted expert and stakeholder interviews across healthcare transformation, patient experience and business research projects.",
        "skills": ["Interviewing", "Research synthesis", "Stakeholder listening", "Insight generation"],
    },
]

skills = {
    "Business & Commercial Execution": [
        "Business ownership",
        "Revenue growth",
        "Stakeholder activation",
        "Commercial follow-up",
        "Pricing thinking",
        "Execution discipline",
    ],
    "Strategy & Transformation": [
        "Market entry strategy",
        "Operating model design",
        "Digital transformation",
        "Ecosystem analysis",
        "Scenario analysis",
        "TOWS / SWOT",
    ],
    "Data Analytics & BI": [
        "Dashboards",
        "EDA",
        "KPI tracking",
        "Regression",
        "Classification",
        "Clustering",
        "Association rule mining",
    ],
    "Healthcare & Life Sciences": [
        "Patient journey mapping",
        "Healthcare operations",
        "Clinical workflow understanding",
        "Market research",
        "Scientific communication",
        "Digital health strategy",
    ],
    "Tools": [
        "Excel",
        "PowerPoint",
        "Power BI",
        "Tableau",
        "Python",
        "Streamlit",
        "SmartPLS",
        "AI tools",
    ],
}

skill_notes = {
    "Business & Commercial Execution": {
        "evidence": "Turfo operating ownership, revenue tracking, pricing decisions, stakeholder handling and high-volume EdTech performance delivery.",
        "methods": "Revenue tracking · Pricing thinking · Stakeholder coordination · Execution discipline",
    },
    "Strategy & Transformation": {
        "evidence": "Consulting-style MBA projects across fintech, healthcare, enterprise systems, life sciences and digital trade.",
        "methods": "Market entry · Operating model design · TOWS/SWOT · Scenario analysis",
    },
    "Data Analytics & BI": {
        "evidence": "TasteMate dashboard, Turfo revenue/utilisation trackers, BYJU’S engagement analytics and AI adoption modelling.",
        "methods": "EDA · Regression · Classification · Clustering · KPI dashboards",
    },
    "Healthcare & Life Sciences": {
        "evidence": "BDS clinical experience, healthcare operations, digital health strategy, patient journey work and life sciences market intelligence.",
        "methods": "Patient journey mapping · Clinical workflow · Research synthesis · Healthcare strategy",
    },
    "Tools": {
        "evidence": "Used across dashboards, analysis, modelling, reporting, presentations and portfolio development.",
        "methods": "Excel · PowerPoint · Power BI · Tableau · Python · Streamlit · SmartPLS · AI tools",
    },
}

skills_visuals = {
    "Business & Commercial Execution": {
        "image": "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1400&q=85",
        "headline": "Execution, ownership and commercial discipline",
    },
    "Strategy & Transformation": {
        "image": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1400&q=85",
        "headline": "Structured business problem solving across markets and systems",
    },
    "Data Analytics & BI": {
        "image": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1400&q=85",
        "headline": "Dashboards, modelling and decision intelligence",
    },
    "Healthcare & Life Sciences": {
        "image": "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1400&q=85",
        "headline": "Clinical grounding plus healthcare strategy exposure",
    },
    "Tools": {
        "image": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1400&q=85",
        "headline": "Practical stack for analysis, reporting and portfolio building",
    },
}
